### ISSUE TITLE
themes are not there

### ISSUE THREAD

**Issue by Techout592** [OreoKitten/DashactylThemes#1]
Hello,

I can't seem to locate the themes, Could you perhaps upload the themes again, please?

Best Regards

**Comment by OreoKitten** [comment]
Hello Techout, 

The themes were not published yet as they are still being modified, and I need to get permission from the other builders of the themes before posting them.

Sincerely,
Oreo Kitten

**Comment by Techout592** [comment]
Hey,

Oh okay,  thanks.

Regards,
Techout
